### PR TITLE
fix 'Good Service' message not showing / showing incorrectly

### LINKED ISSUE #396: List view - good service is repeated twice
On list view we say twice if there is good service. Can we just say it once please. 

IMG_3604

Screenshot 2020-10-28 at 11 40 21

### PR DESCRIPTION
**Pull request by gldgrnt**
Updates the showing of the 'Good Service' message. Fixes #396 

Also addresses issue mentioned in the [Tram stop by stop PR](https://github.com/wmcadigital/wmn-disruptions/pull/424#pullrequestreview-547258643).

### CODE REVIEW

**Comment by daylesalmon** [comment]
Bug spotted:

image

The "save your routes..." message appears on page load and then when you click a service it then snaps to the input. 
If I remember correctly, this message should only appear when there are results from the autocomplete.

File: src/components/shared/Tray/TrayComponents/SelectedService/SelectedService.js [hunk 1]
```diff
@@ -1,35 +1,32 @@
...
   return (
     <>
       {/* If ann item has been selected that is not by the map then show selected services that you can fav and also show save message box. selectedItem.severity is used as the if statement to ensure all other data has been mapped to the state, using the id would cause an error as this can be gotten from the URL */}
-      {autoCompleteState.selectedItem.severity && !autoCompleteState.selectedItem.selectedByMap && (
-        <>
-          <hr className="wmnds-col-1" />
-          <SaveRoutesMessage />
-          <InfoAboutSelectedService />
-        </>
-      )}
```
Comment (daylesalmon) [inline src/components/shared/Tray/TrayComponents/SelectedService/SelectedService.js]: By moving this out it has caused a bug that i've left as a normal comment on this PR.

File: src/components/shared/Tray/TrayComponents/SelectedService/customHooks/useShowSelectedServiceInfo.js [hunk 2]
```diff
@@ -0,0 +1,87 @@
+import { useContext } from 'react';
+import { FetchDisruptionsContext, AutoCompleteContext, ModeContext } from 'globalState';
+// Import customHooks
+import useFilterLogic from 'customHooks/useFilterLogic';
+
+const useShowSelectedServiceInfo = () => {
+  const [{ isMapVisible }] = useContext(FetchDisruptionsContext);
```
Comment (daylesalmon) [inline src/components/shared/Tray/TrayComponents/SelectedService/customHooks/useShowSelectedServiceInfo.js:7]: Double destructure...nice. 
Be careful not to overuse this in future as it can cause confusion.

For now, as it is one item, it is simple enough to understand.

**Review by daylesalmon — CHANGES_REQUESTED** [review]
Just fix the bug that has been caused and all should be good.

File: src/components/shared/Tray/TrayComponents/SelectedService/SelectedService.js [hunk 3]
```diff
@@ -1,35 +1,36 @@
...
         <>
-          <hr className="wmnds-col-1" />
           <SaveRoutesMessage />
           <InfoAboutSelectedService />
         </>
       )}
       {/* If no selectedData then it must be good service */}
-      {!selectedData.length && <Message />}
+      {showServiceMessage && <Message />}
       {/* If there are selectedData then there must be disruptions, loop through */}
```
Comment (daylesalmon) [inline src/components/shared/Tray/TrayComponents/SelectedService/SelectedService.js:31]: The purple "save routes" message box no longer appears when clearing localstate.

How it (should) looks on live site:
image


How yours looks:
image

**Review by daylesalmon — CHANGES_REQUESTED** [review]
One minor change

**Review by daylesalmon — APPROVED** [review]

File: src/components/shared/Tray/TrayComponents/SelectedService/SelectedService.js (hunk 3 above)
Comment (daylesalmon) [reply src/components/shared/Tray/TrayComponents/SelectedService/SelectedService.js:31]: Closing...none-issue.
