### PR TITLE
Mobile fixes

### LINKED ISSUE #412: Mobile view - when user clicks on icon
When you click on train disruption on a map it doesn’t automatically scroll to the disruption information and it just shows filters. This makes me think that the click didn’t work. Users will not know to scroll down to see info or that info appeared at the bottom. 
IMG_3777

### LINKED ISSUE #413: Disruption information on mobile
When looking at map view on mobile, if there is an incident, when you click it the test is down below the search information. It is unclear that you need to scroll down. Even on web as the text is big it can be misleading. Can the incident information be a pop up next to the icon? 

Video example of mobile: https://wmcanet-my.sharepoint.com/:v:/g/personal/rachel_foy_tfwm_org_uk/ESCo8-q7J5JOpuWy1cFYfgUBl-DR3elPcfECnN1WJHQ5GA?e=HJ0s47

### LINKED ISSUE #414: Mobile: Change height of the tray line to 3px and give it a border-radius of 3px.
The current tray line is too small on mobile and needs to be made bigger.

I'd suggest changing the height from 1px to 3px and adding a border-radius of 3px to smooth the edges. If there is a way to cap the edges of the line instead of using border-radius, then that would be even better.

Current design:
Screenshot 2020-11-18 at 14 36 55

With the changes applied, It should look like this:
Screenshot 2020-11-18 at 14 33 32

### LINKED ISSUE #415: Mobile: When I select options in the tray and then clear search, the map shows the whole of Europe (video)
If I fully open the tray on mobile, select my mode of transport, clear search whilst still in the tray and then swipe the tray down, the disruptions map is zoomed out really far, showing most of Europe.

This behaviour still happens if I select any method of transport (Bus, Train or Tram), or any time (Now, Tomorrow, Choose date)

This happens in Chrome and Safari on iOS.

Link to video in Google Drive (sorry for the poor quality):
https://drive.google.com/file/d/1uvFSfC1iZhh2POepQoHG4nmCHiZ9gjKg/view?usp=sharing

### LINKED ISSUE #439: Mobile view - tray issue
When I open the tray and then try to swipe it down to reduce the size so I can see the map, page refreshes instead of pushing tray down. After page refreshing tray is sometimes at the bottom but sometimes is still opened. This is not expected behaviour and may cause confusion. I use chrome on apple phone.

### LINKED ISSUE #451: Top of the tray hides behind the map when a disruption is selected (video) iOS - Safari & Chrome browsers
### Bug:
When I select a disruption in the map, the tray expands but the top of the tray is hidden behind the map. I then have to swipe the disruption information section for the top of the tray to expand to the top of the screen and hide the map.

This happens on both Chrome and Safari browsers on my iPhone 11 (iOS 14.3).

https://user-images.githubusercontent.com/62507489/104438652-1f103080-5588-11eb-909e-90b29a2fdfc2.mov

### PR DESCRIPTION
**Pull request by gldgrnt**
This PR addresses multiple issues, namely the mobile tray's appearance and behaviour when the user selects a disruption.

- fixes #439 
- fixes #414 
- fixes #415 
- fixes #413 
- fixes #412 
- fixes #451

### CODE REVIEW

**Review by daylesalmon — APPROVED** [review]
Looking good, great work on this @gldgrnt! 🥳

File: src/components/shared/Tray/useMobileTrayMethods.js [hunk 1]
```diff
@@ -8,40 +8,120 @@ const useMobileTrayMethods = (slideableTray) => {
...
-      ((modeState.mode === 'train' && selectedItem.id && selectedItemTo.id) ||
+      (selectedItem.selectedByMap ||
+        (modeState.mode === 'train' && selectedItem.id && selectedItemTo.id) ||
         (modeState.mode !== 'train' && selectedItem.id)) &&
-      fetchDisruptionsState.data.length
+      fetchDisruptionsState.data.length &&
+      innerTray
     ) {
       setTrayPosition(half || initialTrayPosition); // set tray to open
+      scrollToServiceInfo(); // scroll down to the relevatnt info in the tray
```
Comment (daylesalmon) [inline src/components/shared/Tray/useMobileTrayMethods.js]:
```suggestion
      scrollToServiceInfo(); // scroll down to the relevant info in the tray
```

**Review by daylesalmon — CHANGES_REQUESTED** [review]
Great work with all these fixes!
Just one minor typo and ready to merge.

**Review by daylesalmon — APPROVED** [review]
